"""High-level PR creator — turns Mutations into real GitHub PRs.

Flow per mutation:
1. Create branch  `eva/<mutation-id>` from default branch
2. Commit the diff to target_path on that branch
3. Open PR with mutation context
4. Label with `eva`, mutation type
5. Update mutation.pr_url
"""

import base64
import os
from dataclasses import dataclass

from rich.console import Console

from eva.core.models import Mutation
from eva.github.client import GitHubClient

console = Console()

# Default labels Eva adds to every PR
EVA_LABELS = ["eva", "automated"]

PR_BODY_TEMPLATE = """\
## Eva — automated mutation

| Field | Value |
|-------|-------|
| **Mutation** | `{mutation_id}` |
| **Type** | `{mutation_type}` |
| **Pattern** | `{pattern_id}` |
| **Confidence** | {confidence:.0%} |
| **Target** | `{target_path}` |

### Description

{description}

### Proposed diff

```diff
{diff}
```

---

> This PR was generated by **Eva** — the meta-evolution Mother agent.
> It requires human review before merging.
> Confidence: **{confidence:.0%}** — {confidence_note}
"""


def _confidence_note(c: float) -> str:
    if c >= 0.8:
        return "High confidence. Review recommended but likely safe."
    if c >= 0.5:
        return "Medium confidence. Please review carefully."
    return "Low confidence. Manual verification required."


@dataclass
class PRCreationResult:
    """Result of attempting to create a PR for a mutation."""

    mutation_id: str
    success: bool
    pr_url: str = ""
    error: str = ""


class PRCreator:
    """Creates GitHub PRs from Eva mutations."""

    def __init__(self, token: str | None = None) -> None:
        self._token = token or os.environ.get("EVA_GITHUB_TOKEN", "")
        if not self._token:
            raise ValueError(
                "No GitHub token available. Set EVA_GITHUB_TOKEN or pass token explicitly."
            )
        self._client = GitHubClient(self._token)

    async def create_pr(self, mutation: Mutation) -> PRCreationResult:
        """Create a PR for a single mutation.

        Returns PRCreationResult with success status and PR URL.
        """
        try:
            repo = mutation.target_repo
            branch = mutation.branch_name

            # 1. Get default branch SHA
            default_branch = await self._client.get_default_branch(repo)
            base_sha = await self._client.get_ref_sha(repo, default_branch)

            console.print(
                f"    [dim]Creating branch {branch} from {default_branch} ({base_sha[:8]})[/dim]"
            )

            # 2. Create branch
            await self._client.create_branch(repo, branch, base_sha)

            # 3. Commit the diff/content to target path
            commit_msg = (
                f"eva: {mutation.title}\n\n"
                f"Mutation: {mutation.id}\n"
                f"Pattern: {mutation.pattern_id}\n"
                f"Confidence: {mutation.confidence:.0%}\n\n"
                f"Auto-generated by Eva. Requires human review."
            )

            # Read existing file content and append/prepend the diff
            existing = await self._client.get_file_content(
                repo, mutation.target_path, default_branch
            )
            if existing and "content" in existing:
                current_content = base64.b64decode(existing["content"]).decode()
                new_content = _apply_mutation(current_content, mutation)
            else:
                new_content = mutation.diff

            await self._client.create_or_update_file(
                repo=repo,
                path=mutation.target_path,
                content=new_content,
                message=commit_msg,
                branch=branch,
            )

            # 4. Open PR
            pr_body = PR_BODY_TEMPLATE.format(
                mutation_id=mutation.id,
                mutation_type=mutation.type.value,
                pattern_id=mutation.pattern_id,
                confidence=mutation.confidence,
                target_path=mutation.target_path,
                description=mutation.description,
                diff=mutation.diff,
                confidence_note=_confidence_note(mutation.confidence),
            )

            pr_result = await self._client.create_pull_request(
                repo=repo,
                title=f"[Eva] {mutation.title}",
                body=pr_body,
                head=branch,
                base=default_branch,
            )

            # 5. Label
            await self._client.add_labels(
                repo,
                pr_result.pr_number,
                EVA_LABELS + [f"eva:{mutation.type.value}"],
            )

            # 6. Update mutation
            mutation.pr_url = pr_result.pr_url

            console.print(f"    [green]✓[/green] PR created: {pr_result.pr_url}")

            return PRCreationResult(
                mutation_id=mutation.id,
                success=True,
                pr_url=pr_result.pr_url,
            )

        except Exception as e:
            console.print(f"    [red]✗[/red] Failed: {e}")
            return PRCreationResult(
                mutation_id=mutation.id,
                success=False,
                error=str(e),
            )

    async def create_all(self, mutations: list[Mutation]) -> list[PRCreationResult]:
        """Create PRs for all mutations (sequentially to avoid rate limits)."""
        results: list[PRCreationResult] = []
        for mutation in mutations:
            result = await self.create_pr(mutation)
            results.append(result)
        return results


def _apply_mutation(current_content: str, mutation: Mutation) -> str:
    """Apply mutation diff to existing file content.

    For now, appends the Eva-generated content at the end.
    Future: parse unified diff and apply properly.
    """
    separator = "\n\n"

    # Extract the actual content from the diff (skip comment lines)
    diff_lines = mutation.diff.strip().split("\n")
    content_lines = []
    for line in diff_lines:
        if line.startswith("# "):
            # Convert comment to markdown
            content_lines.append(line[2:])
        else:
            content_lines.append(line)

    addition = "\n".join(content_lines)

    return current_content.rstrip() + separator + addition + "\n"
