"""Research source — reads improvement proposals generated by the Researcher agent."""

from __future__ import annotations

import re
from pathlib import Path

from eva.core.config import SourceConfig
from eva.core.models import Severity, Signal, SignalType
from eva.sources.base import BaseSource

# Parse PROP files for key metadata
_SCORE_PATTERN = re.compile(r"Applicability:\s*(\d)/5")
_EFFORT_PATTERN = re.compile(r"Effort:\s*(low|medium|high)", re.IGNORECASE)
_IMPACT_PATTERN = re.compile(r"Impact:\s*(.+?)$", re.MULTILINE)

_EFFORT_SEVERITY = {
    "low": Severity.HIGH,      # easy win — prioritize
    "medium": Severity.MEDIUM,
    "high": Severity.LOW,      # heavy lift — lower priority
}


class ResearchSource(BaseSource):
    """Scans spec/research/ for PROP-*.md files generated by the Researcher agent."""

    name = "research"

    def __init__(
        self,
        config: SourceConfig,
        research_dir: Path | None = None,
    ) -> None:
        super().__init__(config)
        self._research_dir = research_dir
        self._seen_ids: set[str] = set()

    async def poll(self) -> list[Signal]:
        if not self._research_dir or not self._research_dir.exists():
            return []

        signals: list[Signal] = []

        for prop_file in sorted(self._research_dir.glob("PROP-*.md")):
            prop_id = prop_file.stem
            if prop_id in self._seen_ids:
                continue
            self._seen_ids.add(prop_id)

            content = prop_file.read_text()
            title = _extract_title(content, prop_id)

            # Extract scores
            score_match = _SCORE_PATTERN.search(content)
            applicability = int(score_match.group(1)) if score_match else 3

            effort_match = _EFFORT_PATTERN.search(content)
            effort = effort_match.group(1).lower() if effort_match else "medium"

            impact_match = _IMPACT_PATTERN.search(content)
            impact = impact_match.group(1).strip() if impact_match else ""

            severity = _EFFORT_SEVERITY.get(effort, Severity.MEDIUM)
            # Boost severity for high-applicability proposals
            if applicability >= 4 and severity != Severity.HIGH:
                severity = Severity.HIGH

            signal = Signal(
                id=prop_id,
                type=SignalType.RESEARCH_PROPOSAL,
                source=f"research:{prop_file.name}",
                title=title,
                body=content,
                severity=severity,
                metadata={
                    "applicability": applicability,
                    "effort": effort,
                    "impact": impact,
                    "file": str(prop_file),
                },
                tags=["research", effort, f"score-{applicability}"],
            )
            signals.append(signal)

        return signals

    async def healthcheck(self) -> bool:
        return self._research_dir is not None and self._research_dir.exists()


def _extract_title(content: str, fallback: str) -> str:
    """Extract title from first H1 header."""
    for line in content.splitlines():
        if line.startswith("# PROP:"):
            return line.replace("# PROP:", "").strip()
        if line.startswith("# "):
            return line.lstrip("# ").strip()
    return fallback
